# 1. Selección de Datos y Planteamiento de Hipótesis

## 1.1 Justificación de la Fuente de Datos
Para este proyecto, hemos decidido trabajar con el dataset de **Precios Históricos del S&P 500**. 

**Se eligieron 11 empresas, pero ¿Porque se seleccionaron especificamente esas 11?**
No elegimos empresas al azar, se selecciono un portafolio que mezcla dos mundos opuestos:
1.  **Los Gigantes Tecnológicos:** Apple, Microsoft, Nvidia, Google, Amazon, Meta, Netflix y Tesla. Son empresas que crecen mucho pero son muy sensibles a las crisis.
2.  **El Consumo Estable:** Coca-Cola, Pepsi y McDonald's. Son empresas que la gente sigue usando incluso si hay crisis, por lo que sirven como "punto de control" para comparar qué tan inestables son los movimientos de las empresas tecnológicas.

---

## 1.2 Hipótesis y Expectativas del Análisis
*Antes de analizar los resultados finales, planteamos lo que nuestra intuición (y las noticias recientes) nos dice que deberíamos encontrar:*

### Hipótesis 1: El Shock Global de la Pandemia (Marzo 2020)
**Contexto:** En marzo de 2020, el mundo se detuvo por el COVID-19. 
**Hipótesis:** Esperamos ver una "caída en picada" casi vertical en todas las líneas del gráfico. Sin embargo, nuestra hipótesis es que las empresas tecnológicas de Streaming (como Amazon o Netflix) se recuperarán mucho más rápido que las demás, ya que el confinamiento obligó a todo el mundo a usar servicios digitales, acelerando su crecimiento.



### Hipótesis 2: El Auge de la Inteligencia Artificial (2023-2024)
**Contexto:** A finales de 2022 y principios de 2023, la IA (como ChatGPT) cambió las reglas del juego.
**Hipótesis:** Predecimos que empresas de hardware y software como **Nvidia** y **Microsoft** mostrarán una pendiente de subida mucho más empinada que el resto del mercado. Creemos que este será el evento más visible en la segunda mitad de nuestro gráfico, marcando una diferencia gigante con empresas tradicionales.



### Hipótesis 3: La Diferencia de Volatilidad
**Contexto:** No todas las acciones se mueven igual. 
**Hipótesis:** Esperamos que las líneas de **Coca-Cola (KO)** y **Pepsi (PEP)** sean mucho más suaves y persistentes. Por el contrario, empresas como **Tesla (TSLA)** o **Nvidia (NVDA)** deberían mostrar picos y valles muy pronunciados. Esto nos servirá para demostrar que el riesgo de inversión es mucho mayor en el sector tecnológico que en el de consumo básico.

### Hipótesis 4: La Caída por Inflación (2022)
**Contexto:** Durante el 2022, hubo mucha incertidumbre económica y subida de precios a nivel mundial.
**Hipótesis:** Esperamos ver un periodo de decadencia donde la mayoría de los activos perdieron valor. Nuestra intuición es que este periodo servirá para limpiar el exceso de optimismo de la post-pandemia antes del nuevo salto de la IA.

In [2]:
#Cargamos todas las librerias necesarias para el proyecto.
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import requests #Libreria necesaria para adquirir datos desde una API 
import io #Libreria necesaria para descomprimir archivo .zip de la base de datos sin necesidad de descargarlo en disco.
from collections import Counter #Libreria para contar.
import mplfinance as mpf #Libreria especializada en hacer graficos de velas con volumen.
from statsmodels.graphics.tsaplots import plot_acf #Libreria para medir la autocorrelacion de precios dependiendo del tiempo.
from statsmodels.tsa.seasonal import seasonal_decompose #Libreria que grafica la Tendencia, Estacionalidad y Residuo de las acciones.

In [4]:
#Se comienza la obtencion de datos desde la API

#URL de la API que utilizaremos
URL = "https://www.kaggle.com/api/v1/datasets/download/yash16jr/s-and-p500-daily-update-dataset"

#Se le piden los datos a la API de Kaggle
response = requests.get(URL)

#Nos imprime el codigo de respuesta, si el codigo es [200] se adquirio de manera correcta la base de datos desde la API.
print(response)

#Se verifica el tamaño del archivo para ver si se adquirio completa la base de datos, debiendo pesar aprox 71mb
print(f"El tamaño del archivo es de {len(response.content)*1e-6} mb")

<Response [200]>
El tamaño del archivo es de 70.579545 mb

In [5]:
#Creamos el objeto con los datos
datos = io.BytesIO(response.content)

#Cargamos directamente a un DataFrame (Pandas se encarga de descomprimir el .zip)
df = pd.read_csv(datos, compression="zip", low_memory=False)

print("Datos Cargados con Exito!")

Datos Cargados con Exito!

## 2. Analisis de Datos Crudos
 
*Se procede a hacer un analisis inicial de los datos para ver como estan distribuidos los datos y que tipo de datos se tienen en la muestra.*

In [8]:
#Vista inicial de los primeros datos utilizando .head()
print("Los primeros datos son:")
df.head()

Los primeros datos son:

        Price               Close  ... Volume.501 Volume.502
0      Ticker                   A  ...       ZBRA        ZTS
1        Date                 NaN  ...        NaN        NaN
2  2010-01-04  19.856182098388672  ...     168800        NaN
3  2010-01-05  19.640501022338867  ...     168800        NaN
4  2010-01-06  19.570714950561523  ...     385300        NaN

[5 rows x 2516 columns]

In [9]:
#Vista inicial de los ultimos datos utilizando .tail()
print("Los ultimos datos son:")
df.tail()

Los ultimos datos son:

           Price               Close  ... Volume.501 Volume.502
4080  2026-03-23   112.0199966430664  ...     602400  4617900.0
4081  2026-03-24  114.19999694824219  ...     425000  4561800.0
4082  2026-03-25   112.9800033569336  ...     456800  3078900.0
4083  2026-03-26   113.4800033569336  ...     415000  2725900.0
4084  2026-03-27  110.23999786376953  ...     594500  3601800.0

[5 rows x 2516 columns]

In [27]:
#Analisis inicial
print("1. Dimensiones del DataSet")
print(f"La muestra tiene {df.shape[0]} Filas y {df.shape[1]} Columnas")

print("\n2. Tipos de Variables")
print("Los datos son del tipo:")
#Nota: Hacemos .iloc ya que la primera fila es strings y la segunda pareciera que son NaN 
valor_fila3 = df.iloc[2].apply(type) 
print(valor_fila3)


print("\n3. Rango Temporal")
#Nota: Utilizaremos .iloc porque las fechas se encuentran en la columna 0 y desde la fila 2 en adelante.
fechas = pd.to_datetime(df.iloc[2:,0])
print(f"Los datos comienzan en la fecha {fechas.min()} y terminan en {fechas.max()}")
print(f"Por lo que el tiempo total de la muestra es de {fechas.max()-fechas.min()}")

print("\n4. Conteo de Valores Nulos (Total en la Muestra)")
print(f"En la muestra existen {df.isnull().sum().sum()} datos nulos")

1. Dimensiones del DataSet
La muestra tiene 4085 Filas y 2516 Columnas

2. Tipos de Variables
Los datos son del tipo:
Price           <class 'str'>
Close           <class 'str'>
Close.1         <class 'str'>
Close.2       <class 'float'>
Close.3       <class 'float'>
                   ...
Volume.498    <class 'float'>
Volume.499      <class 'str'>
Volume.500      <class 'str'>
Volume.501      <class 'str'>
Volume.502    <class 'float'>
Name: 2, Length: 2516, dtype: object

3. Rango Temporal
Los datos comienzan en la fecha 2010-01-04 00:00:00 y terminan en 2026-03-27 00:00:00
Por lo que el tiempo total de la muestra es de 5926 days 00:00:00

4. Conteo de Valores Nulos (Total en la Muestra)
En la muestra existen 603735 datos nulos

### 2.1 Interpretación de Hallazgos Preliminares

Tras ejecutar el diagnóstico inicial sobre los datos crudos de la muestra, se identifican los siguientes puntos críticos que definen el objetivo para la fase de limpieza:

* **Discrepancia en la Densidad Temporal:** Se observa un rango de **5,926 días de calendario**, pero solo **4,083 filas donde se registran dias** efectivos. No se puede asumir que esta diferencia corresponde exclusivamente a feriados, existe la posibilidad de tener **vacíos de información o fallos en la captura de datos** por parte de la API. Esta incertidumbre será un factor a considerar al evaluar la continuidad de las series de tiempo.

* **Naturaleza de las Variables (Tipos de Datos):** Al revisar el resumen de la muestra, nos dimos cuenta de que las columnas de precios aparecen marcadas como **texto (`str`)** en lugar de números. Esto sucede porque en las primeras filas del archivo se colaron palabras como "Ticker", "A" o "Date", que vienen de la configuración original de la API. Como Python encuentra estas palabras al principio, asume que toda la columna es de texto. Esto hace que el dataset sea **matemáticamente inutilizable** por el momento, ya que no se pueden realizar cálculos de rendimiento, promedios o gráficos de volatilidad con "palabras". Para avanzar, será obligatorio limpiar esas filas de títulos y transformar los datos restantes en números reales para que el programa pueda procesarlos correctamente.

* **Integridad y Dispersión del Dataset:** La presencia de **603,735 valores nulos** sugiere que estamos ante una "matriz dispersa". Dado que manejamos 2,516 columnas, es altamente probable que muchos activos no posean registros para la totalidad del periodo (2010-2026). Esto justifica la necesidad de un proceso posterior de filtrado para conservar solo aquellos activos con datos íntegros.

* **Conclusión del Diagnóstico:** La muestra posee un alcance temporal que cubre hitos históricos clave, pero su calidad actual es baja debido a la inconsistencia de tipos y la alta tasa de nulos. Estos resultados validan la necesidad de proceder con una fase de **limpieza de datos** para transformar estos datos crudos en información analizable.

## 2.2 Limpieza de Datos y Eleccion de Empresas
*Ya con los datos crudos analizados se encontraron diversos problemas, debido a esto se procedera a realizar la limpieza de los datos y la eleccion de las empresas a las cuales se les realizara el analisis final.*